development:
  cloud_name: dszzio77r
  api_key: '128596514214396'
  api_secret: pz3Mc1jG9Uh7VMxA0JLOQAVbMs0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dszzio77r
  api_key: '128596514214396'
  api_secret: pz3Mc1jG9Uh7VMxA0JLOQAVbMs0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dszzio77r
  api_key: '128596514214396'
  api_secret: pz3Mc1jG9Uh7VMxA0JLOQAVbMs0
  enhance_image_tag: true
  static_image_support: false
